version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: IMSDB_Backend
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring_net

volumes:
  postgres_data:

networks:
  spring_net: